//! Pure state machine for task lifecycle transitions.
//!
//! [`TaskStateMachine`] is the single source of truth for valid state transitions.
//! It is deterministic, side-effect free (except for updating the passed [`Task`]),
//! and produces an [`Event`](crate::task::Event) for every transition.
//!
//! # Usage
//!
//! ```
//! use adp_core::state_machine::{TaskStateMachine, TransitionCommand};
//! use adp_core::task::{Id, Task};
//!
//! let mut task = Task::builder("example").build();
//! let sm = TaskStateMachine::new();
//! let events = sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() }).unwrap();
//! assert_eq!(task.state, adp_core::task::TaskState::Delegated);
//! ```

use crate::error::{AdpError, Result};
use crate::task::{Event, EventType, Id, Task, TaskState};
use chrono::Utc;
use tracing::{info, instrument};

/// Validates and executes state transitions for a single task.
#[derive(Debug, Clone, Default)]
pub struct TaskStateMachine;

/// Commands that drive state transitions.
///
/// These represent external inputs to the state machine: an agent reporting
/// completion, the scheduler spawning subtasks, a timeout triggering failure, etc.
#[derive(Debug, Clone, PartialEq)]
pub enum TransitionCommand {
    /// Assign the task to an agent.
    Delegate { agent_id: Id },
    /// Agent has started executing the task.
    StartExecution,
    /// Task completed successfully with a result payload.
    Complete { result: serde_json::Value },
    /// Task failed with a reason.
    Fail { reason: String },
    /// Task spawned subtasks and is now waiting for them.
    SpawnSubtasks { subtask_ids: Vec<Id> },
    /// All subtasks have reached a terminal state.
    SubtasksCompleted,
    /// Aggregate subtask results and mark the parent complete.
    Aggregate { result: serde_json::Value },
    /// Retry a failed task.
    Retry,
    /// Explicitly cancel the task (e.g., BROADCAST losers).
    Cancel { reason: String },
}

impl TaskStateMachine {
    /// Create a new state machine instance.
    pub fn new() -> Self {
        Self
    }

    /// Apply a transition command to a task.
    ///
    /// Returns the audit events generated by this transition. The task is updated
    /// in-place for ergonomics, but callers **must** persist both the task and
    /// events to the store.
    ///
    /// # Errors
    ///
    /// - [`AdpError::InvalidStateTransition`] if the command is not valid for the current state.
    /// - [`AdpError::TerminalState`] if the task is already in a terminal state.
    /// - [`AdpError::DelegationFailed`] if retry is attempted but max retries exceeded.
    #[instrument(skip(self, task), fields(task_id = %task.id, current_state = %task.state))]
    pub fn apply(&self, task: &mut Task, cmd: TransitionCommand) -> Result<Vec<Event>> {
        let from = task.state;
        let to = self.compute_new_state(task, &cmd)?;

        if from == to {
            // Idempotent: no transition, no event.
            return Ok(Vec::new());
        }

        self.validate_transition(from, to)?;

        task.state = to;
        task.updated_at = Utc::now();

        if to == TaskState::Completed {
            task.completed_at = Some(Utc::now());
        }

        // Apply command-specific side effects to the task struct.
        match &cmd {
            TransitionCommand::Delegate { agent_id } => {
                task.agent_id = Some(*agent_id);
            }
            TransitionCommand::SpawnSubtasks { subtask_ids } => {
                task.subtask_ids.extend(subtask_ids.iter().copied());
            }
            TransitionCommand::Retry => {
                task.retry_count += 1;
                task.agent_id = None;
                task.completed_at = None;
            }
            _ => {}
        }

        let event = Event {
            id: Id::new(),
            task_id: task.id,
            event_type: Self::event_type_for_command(&cmd),
            from_state: Some(from),
            to_state: Some(to),
            payload: Self::payload_for_command(&cmd),
            created_at: Utc::now(),
        };

        info!(
            from_state = %from,
            to_state = %to,
            task_id = %task.id,
            "task state transition"
        );

        Ok(vec![event])
    }

    /// Compute the target state for a (current_state, command) pair.
    ///
    /// This encodes the primary transition rules. It may inspect task fields
    /// (e.g., `retry_count`) to determine validity.
    fn compute_new_state(&self, task: &Task, cmd: &TransitionCommand) -> Result<TaskState> {
        match (task.state, cmd) {
            // PENDING
            (TaskState::Pending, TransitionCommand::Delegate { .. }) => Ok(TaskState::Delegated),
            (TaskState::Pending, TransitionCommand::Cancel { .. }) => Ok(TaskState::Cancelled),

            // DELEGATED
            (TaskState::Delegated, TransitionCommand::StartExecution) => Ok(TaskState::Executing),
            (TaskState::Delegated, TransitionCommand::Fail { .. }) => Ok(TaskState::Failed),
            (TaskState::Delegated, TransitionCommand::Cancel { .. }) => Ok(TaskState::Cancelled),

            // EXECUTING
            (TaskState::Executing, TransitionCommand::Complete { .. }) => Ok(TaskState::Completed),
            (TaskState::Executing, TransitionCommand::Fail { .. }) => Ok(TaskState::Failed),
            (TaskState::Executing, TransitionCommand::SpawnSubtasks { .. }) => {
                Ok(TaskState::AwaitingSubtasks)
            }
            (TaskState::Executing, TransitionCommand::Cancel { .. }) => Ok(TaskState::Cancelled),

            // AWAITING_SUBTASKS
            (TaskState::AwaitingSubtasks, TransitionCommand::SubtasksCompleted) => {
                Ok(TaskState::Aggregating)
            }
            (TaskState::AwaitingSubtasks, TransitionCommand::Fail { .. }) => Ok(TaskState::Failed),
            (TaskState::AwaitingSubtasks, TransitionCommand::Cancel { .. }) => {
                Ok(TaskState::Cancelled)
            }

            // AGGREGATING
            (TaskState::Aggregating, TransitionCommand::Aggregate { .. }) => {
                Ok(TaskState::Completed)
            }
            (TaskState::Aggregating, TransitionCommand::Fail { .. }) => Ok(TaskState::Failed),
            (TaskState::Aggregating, TransitionCommand::Cancel { .. }) => Ok(TaskState::Cancelled),

            // FAILED → retry
            (TaskState::Failed, TransitionCommand::Retry) => {
                if task.can_retry() {
                    Ok(TaskState::Delegated)
                } else {
                    Err(AdpError::DelegationFailed(
                        "max retries exceeded".to_string(),
                    ))
                }
            }

            // Terminal states block all commands.
            (state, _) if task.is_terminal() => Err(AdpError::TerminalState(state)),

            // Everything else is invalid.
            _ => Err(AdpError::InvalidStateTransition { from: task.state, to: task.state }),
        }
    }

    /// Defense-in-depth: validate that a from→to pair is legal.
    ///
    /// This is a redundant check after `compute_new_state` but ensures that
    /// even if the command logic is bypassed, illegal transitions are rejected.
    fn validate_transition(&self, from: TaskState, to: TaskState) -> Result<()> {
        let valid = matches!(
            (from, to),
            // Standard flow
            (TaskState::Pending, TaskState::Delegated)
                | (TaskState::Delegated, TaskState::Executing)
                | (TaskState::Executing, TaskState::Completed)
                | (TaskState::Executing, TaskState::AwaitingSubtasks)
                | (TaskState::AwaitingSubtasks, TaskState::Aggregating)
                | (TaskState::Aggregating, TaskState::Completed)
                // Failure from any non-terminal state
                | (TaskState::Pending, TaskState::Failed)
                | (TaskState::Delegated, TaskState::Failed)
                | (TaskState::Executing, TaskState::Failed)
                | (TaskState::AwaitingSubtasks, TaskState::Failed)
                | (TaskState::Aggregating, TaskState::Failed)
                // Retry
                | (TaskState::Failed, TaskState::Delegated)
                // Cancellation
                | (TaskState::Pending, TaskState::Cancelled)
                | (TaskState::Delegated, TaskState::Cancelled)
                | (TaskState::Executing, TaskState::Cancelled)
                | (TaskState::AwaitingSubtasks, TaskState::Cancelled)
                | (TaskState::Aggregating, TaskState::Cancelled)
        );

        if valid {
            Ok(())
        } else {
            Err(AdpError::InvalidStateTransition { from, to })
        }
    }

    fn event_type_for_command(cmd: &TransitionCommand) -> EventType {
        match cmd {
            TransitionCommand::Delegate { .. } => EventType::DelegationCreated,
            TransitionCommand::StartExecution => EventType::StateTransition,
            TransitionCommand::Complete { .. } => EventType::StateTransition,
            TransitionCommand::Fail { .. } => EventType::StateTransition,
            TransitionCommand::SpawnSubtasks { .. } => EventType::SubtaskCreated,
            TransitionCommand::SubtasksCompleted => EventType::StateTransition,
            TransitionCommand::Aggregate { .. } => EventType::StateTransition,
            TransitionCommand::Retry => EventType::RetryTriggered,
            TransitionCommand::Cancel { .. } => EventType::Cancelled,
        }
    }

    fn payload_for_command(cmd: &TransitionCommand) -> serde_json::Value {
        match cmd {
            TransitionCommand::Delegate { agent_id } => {
                serde_json::json!({ "agent_id": agent_id.to_string() })
            }
            TransitionCommand::Complete { result } => {
                serde_json::json!({ "result": result })
            }
            TransitionCommand::Fail { reason } => {
                serde_json::json!({ "reason": reason })
            }
            TransitionCommand::SpawnSubtasks { subtask_ids } => {
                serde_json::json!({
                    "subtask_ids": subtask_ids.iter().map(|id| id.to_string()).collect::<Vec<_>>()
                })
            }
            TransitionCommand::Aggregate { result } => {
                serde_json::json!({ "result": result })
            }
            TransitionCommand::Retry => serde_json::Value::Null,
            TransitionCommand::Cancel { reason } => {
                serde_json::json!({ "reason": reason })
            }
            _ => serde_json::Value::Null,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_task() -> Task {
        Task::builder("test.task").build()
    }

    #[test]
    fn pending_to_delegated() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        let events = sm
            .apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        assert_eq!(task.state, TaskState::Delegated);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].event_type, EventType::DelegationCreated);
    }

    #[test]
    fn delegated_to_executing() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        let events = sm
            .apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        assert_eq!(task.state, TaskState::Executing);
        assert_eq!(events.len(), 1);
    }

    #[test]
    fn executing_to_completed() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        let events = sm
            .apply(
                &mut task,
                TransitionCommand::Complete {
                    result: serde_json::Value::Null,
                },
            )
            .unwrap();
        assert_eq!(task.state, TaskState::Completed);
        assert_eq!(events.len(), 1);
        assert!(task.completed_at.is_some());
    }

    #[test]
    fn executing_to_awaiting_subtasks() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        let events = sm
            .apply(
                &mut task,
                TransitionCommand::SpawnSubtasks {
                    subtask_ids: vec![Id::new(), Id::new()],
                },
            )
            .unwrap();
        assert_eq!(task.state, TaskState::AwaitingSubtasks);
        assert_eq!(task.subtask_ids.len(), 2);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].event_type, EventType::SubtaskCreated);
    }

    #[test]
    fn awaiting_to_aggregating() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::SpawnSubtasks {
                subtask_ids: vec![Id::new()],
            },
        )
        .unwrap();
        let events = sm
            .apply(&mut task, TransitionCommand::SubtasksCompleted)
            .unwrap();
        assert_eq!(task.state, TaskState::Aggregating);
        assert_eq!(events.len(), 1);
    }

    #[test]
    fn aggregating_to_completed() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::SpawnSubtasks {
                subtask_ids: vec![Id::new()],
            },
        )
        .unwrap();
        sm.apply(&mut task, TransitionCommand::SubtasksCompleted)
            .unwrap();
        let events = sm
            .apply(
                &mut task,
                TransitionCommand::Aggregate {
                    result: serde_json::json!({ "sum": 42 }),
                },
            )
            .unwrap();
        assert_eq!(task.state, TaskState::Completed);
        assert_eq!(events.len(), 1);
    }

    #[test]
    fn retry_flow() {
        let mut task = Task::builder("test.task").max_retries(2).build();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::Fail {
                reason: "timeout".to_string(),
            },
        )
        .unwrap();
        assert_eq!(task.state, TaskState::Failed);
        assert_eq!(task.retry_count, 0);

        let events = sm.apply(&mut task, TransitionCommand::Retry).unwrap();
        assert_eq!(task.state, TaskState::Delegated);
        assert_eq!(task.retry_count, 1);
        assert!(task.agent_id.is_none());
        assert_eq!(events[0].event_type, EventType::RetryTriggered);
    }

    #[test]
    fn max_retries_enforced() {
        let mut task = Task::builder("test.task").max_retries(1).build();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::Fail {
                reason: "timeout".to_string(),
            },
        )
        .unwrap();
        sm.apply(&mut task, TransitionCommand::Retry).unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::Fail {
                reason: "timeout".to_string(),
            },
        )
        .unwrap();

        let result = sm.apply(&mut task, TransitionCommand::Retry);
        assert!(matches!(result, Err(AdpError::DelegationFailed(_))));
    }

    #[test]
    fn invalid_transition_fails() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        let result = sm.apply(&mut task, TransitionCommand::StartExecution);
        assert!(matches!(
            result,
            Err(AdpError::InvalidStateTransition { .. })
        ));
    }

    #[test]
    fn terminal_state_blocks_transitions() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        sm.apply(&mut task, TransitionCommand::StartExecution)
            .unwrap();
        sm.apply(
            &mut task,
            TransitionCommand::Complete {
                result: serde_json::Value::Null,
            },
        )
        .unwrap();

        let result = sm.apply(
            &mut task,
            TransitionCommand::Fail {
                reason: "oops".to_string(),
            },
        );
        assert!(matches!(
            result,
            Err(AdpError::TerminalState(TaskState::Completed))
        ));
    }

    #[test]
    fn cancel_from_pending() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        let events = sm
            .apply(
                &mut task,
                TransitionCommand::Cancel {
                    reason: "broadcast loser".to_string(),
                },
            )
            .unwrap();
        assert_eq!(task.state, TaskState::Cancelled);
        assert_eq!(events[0].event_type, EventType::Cancelled);
    }

    #[test]
    fn idempotent_transition() {
        let mut task = test_task();
        let sm = TaskStateMachine::new();
        sm.apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        // Delegating again while already delegated should be a no-op
        let events = sm
            .apply(&mut task, TransitionCommand::Delegate { agent_id: Id::new() })
            .unwrap();
        assert_eq!(events.len(), 0);
        assert_eq!(task.state, TaskState::Delegated);
    }

    // Property-based tests
    use proptest::prelude::*;

    prop_compose! {
        fn arb_task_state()(state in prop_oneof![
            Just(TaskState::Pending),
            Just(TaskState::Delegated),
            Just(TaskState::Executing),
            Just(TaskState::AwaitingSubtasks),
            Just(TaskState::Aggregating),
            Just(TaskState::Completed),
            Just(TaskState::Failed),
            Just(TaskState::Cancelled),
        ]) -> TaskState {
            state
        }
    }

    proptest! {
        #[test]
        fn terminal_state_never_transitions(state in arb_task_state()) {
            let mut task = Task::builder("prop.test").build();
            task.state = state;

            if task.is_terminal() {
                let sm = TaskStateMachine::new();
                let result = sm.apply(
                    &mut task,
                    TransitionCommand::Fail { reason: "test".to_string() }
                );
                prop_assert!(result.is_err());
            }
        }
    }
}
