//! gRPC service definitions (tonic).
//!
//! Provides protobuf-generated services for task management,
//! delegation, and event streaming.

use crate::error::{GatewayError, Result};
use adp_core::scheduler::DagScheduler;
use adp_core::store::{EventStore, TaskStore};
use adp_core::task::{Id, Task, TaskState};
use std::sync::Arc;
use tonic::{Request, Response, Status};
use tracing::{info, instrument};

// Placeholder for generated protobuf service.
// In production, this would be generated by prost from proto files.

/// gRPC service handler for ADP Core.
#[derive(Debug, Clone)]
pub struct AdpGrpcService<S: TaskStore, E: EventStore> {
    scheduler: Arc<DagScheduler<S, E>>,
}

impl<S: TaskStore, E: EventStore> AdpGrpcService<S, E> {
    pub fn new(scheduler: DagScheduler<S, E>) -> Self {
        Self {
            scheduler: Arc::new(scheduler),
        }
    }
}

/// Server builder for the gRPC service.
#[derive(Debug)]
pub struct GrpcServer {
    addr: std::net::SocketAddr,
}

impl GrpcServer {
    pub fn new(addr: std::net::SocketAddr) -> Self {
        Self { addr }
    }

    /// Start the gRPC server.
    pub async fn serve(self) -> Result<()> {
        info!(addr = %self.addr, "gRPC server starting");
        // In production, this would bind a tonic service.
        // Placeholder: just log and return.
        Ok(())
    }
}
